class VietNamLocation{
  static List<String> roviceInfoList = [
  'Tỉnh/ Thành Phố',
  'An Giang',
  'Bà Rịa - Vũng Tàu',
  'Bạc Liêu',
  'Bắc Kạn',
  'Bắc Giang',
  'Bắc Ninh',
  'Bến Tre',
  'Bình Dương',
  'Bình Định',
  'Bình Phước',
  'Bình Thuận',
  'Cà Mau',
  'Cao Bằng',
  'Cần Thơ',
  'Đà Nẵng',
  'Đắk Lắk',
  'Đắk Nông',
  'Điện Biên',
  'Đồng Nai',
  'Đồng Tháp',
  'Gia Lai',
  'Hà Giang',
  'Hà Nam',
  'Hà Nội',
  'Hà Tĩnh',
  'Hải Dương',
  'Hải Phòng',
  'Hậu Giang',
  'Hòa Bình',
  'Hồ Chí Minh',
  'Hưng Yên',
  'Khánh Hòa',
  'Kiên Giang',
  'Kon Tum',
  'Lai Châu',
  'Lâm Đồng',
  'Lạng Sơn',
  'Lào Cai',
  'Long An',
  'Nam Định',
  'Nghệ An',
  'Ninh Bình',
  'Ninh Thuận',
  'Phú Thọ',
  'Phú Yên',
  'Quảng Bình',
  'Quảng Nam',
  'Quảng Ngãi',
  'Quảng Ninh',
  'Quảng Trị',
  'Sóc Trăng',
  'Sơn La',
  'Tây Ninh',
  'Thái Bình',
  'Thái Nguyên',
  'Thanh Hóa',
  'Thừa Thiên Huế',
  'Tiền Giang',
  'Trà Vinh',
  'Tuyên Quang',
  'Vĩnh Long',
  'Vĩnh Phúc',
  'Yên Bái'
  ];

  static List<String> district = [
    'Quận huyện',
  'Huyện',
  'Ba Vì',
  'Chương Mỹ',
  'Đan Phượng',
  'Đông Anh',
  'Gia Lâm',
  'Hoài Đức',
  'Mê Linh',
  'Mỹ Đức',
  'Phú Xuyên',
  'Phúc Thọ',
  'Quốc Oai',
  'Sóc Sơn',
  'Thạch Thất',
  'Thanh Oai',
  'Thanh Trì',
  'Thường Tín',
  'Ứng Hòa'
  ];

  static List<String> getListRovice (){
    return roviceInfoList;
  }static List<String> getListDistrict (){
    return district;
  }
}